import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";

import { R9_OUTPUT_MANIFEST, verifyR9OutputManifest } from "../scripts/lib/r9-manifest-check.mjs";

test("R9 manifest check accepts matching outputs and rejects a changed byte", (t) => {
  const root = mkdtempSync(path.join(os.tmpdir(), "zudo-r9-manifest-"));
  t.after(() => rmSync(root, { recursive: true, force: true }));

  const outputPath = "engineering/r9-prototype-01/out/aluminum/sample.dxf";
  const outputFile = path.join(root, outputPath);
  const manifestFile = path.join(root, R9_OUTPUT_MANIFEST);
  mkdirSync(path.dirname(outputFile), { recursive: true });
  mkdirSync(path.dirname(manifestFile), { recursive: true });

  const original = Buffer.from("first generated bytes\n");
  writeFileSync(outputFile, original);
  writeFileSync(manifestFile, JSON.stringify({
    outputs: [{
      path: outputPath,
      sha256: createHash("sha256").update(original).digest("hex"),
    }],
  }));

  assert.equal(verifyR9OutputManifest(root), 1);

  const changed = Buffer.from(readFileSync(outputFile));
  changed[0] ^= 1;
  writeFileSync(outputFile, changed);
  assert.throws(() => verifyR9OutputManifest(root), /SHA-256 mismatch/);
});
