#!/usr/bin/env node
/* Offline, deterministic build. Writes only to --out or owned publish paths. */
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),os=require('node:os'),cp=require('node:child_process');
const {M,G,D}=require('./load.cjs');
const ROOT=__dirname,REPO=path.resolve(ROOT,'../../..'),args=process.argv.slice(2),check=args.includes('--check');
const oi=args.indexOf('--out');if(oi>=0&&!args[oi+1])throw Error('--out requires directory');
const OUT=check?fs.mkdtempSync(path.join(os.tmpdir(),'two-way-check-')):oi>=0?path.resolve(args[oi+1]):REPO;
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const files=[];function write(name,data){const p=path.join(OUT,name);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,data);files.push(name);}
const json=v=>JSON.stringify(v,null,2)+'\n';
const download='public/downloads/studies/two-way/';
let html=fs.readFileSync(path.join(ROOT,'source/index.template.html'),'utf8');
const inputs={};for(const name of fs.readdirSync(path.join(ROOT,'source')).sort())inputs['engineering/two-way/tw-01/source/'+name]=sha(fs.readFileSync(path.join(ROOT,'source',name)));
inputs['project/two-way/study-spec.json']=sha(fs.readFileSync(path.join(REPO,'project/two-way/study-spec.json')));
html=html.replace('/*SPEC*/',()=> 'globalThis.TwoWaySpec='+JSON.stringify(TwoWaySpec)+';');
for(const [key,name] of Object.entries({FRAMEDATA:'frame-data.js',FRAME:'frame.js',STYLE:'style.css',MODEL:'model.js',RENDERER:'renderer.js',APP:'app.js'}))html=html.replace('/*'+key+'*/',()=>fs.readFileSync(path.join(ROOT,'source',name),'utf8'));
html=html.replace('/*GEOMETRY*/',()=>['base-geometry.inc','frame-geometry.inc','closure.js'].map(f=>fs.readFileSync(path.join(ROOT,'source',f),'utf8')).join('\n'));
html=html.replace('/*HINGEIMAGE*/',()=> 'data:image/png;base64,'+fs.readFileSync(path.join(ROOT,'reference/hinge-user-dimensions.png')).toString('base64'));
// Historical thumbnails must never masquerade as current TW-01 evidence.
html=html.replace('/*THUMBS*/','window.FOLD_THUMBS={};');
if(/\/\*(SPEC|FRAME|FRAMEDATA|MODEL|APP|GEOMETRY|STYLE|RENDERER|HINGEIMAGE|THUMBS)\*\//.test(html))throw Error('Unresolved placeholder');
for(const match of html.matchAll(/<script>([\s\S]*?)<\/script>/g))new (require('node:vm').Script)(match[1]);
if(!html.includes('src="data:image/png;base64,'))throw Error('Missing embedded hinge drawing');
write('public/previews/two-way/tw-01.html',html);
const base=id=>{const p=M.presets[id];return {...M.defaults,preset:id,baseDepth:p.baseDepth,lidDepth:p.lidDepth};};
const rows=[];
for(const [id,p] of Object.entries(M.presets)){
 const s=base(id),d=M.dimensions(s);rows.push({id:p.familyId,letter:p.letter,perTrayU:p.layout,totalU:d.totalU,hp:p.hp,metal:[d.W,d.D,d.metalStack],complete:[d.closedW,d.closedD,d.closedH],trunkInside:d.trunkRequired,baseDepth:s.baseDepth,lidDepth:s.lidDepth,frameReach:d.frame.rearReach,frameRearClearLid:d.frameRearClearLid,countsPerTray:d.frame.counts,manufacturingApproved:false});
 for(const profile of Object.keys(M.profiles))for(const collar of ['loose','hinged']){
  const pro=M.profiles[profile],n={...s,pose:'closed',profile,collar};
  for(const k of ['gap','plugBase','plugLid','bend','knobBase','knobLid','elbow'])n[k]=pro[k];
  write(download+`${p.letter}-${profile}-${collar}-TW-01.json`,json(M.config(n)));
 }
 write(download+`${p.letter}-frame-TW-01.json`,json(M.config({...s,pose:'frame'})));
 for(const pose of ['frame','play'])write(download+`${p.letter}-${pose}-TW-01.glb`,glb({...s,pose}));
}
write('project/two-way/dimensions.json',json(rows));write('src/components/two-way-data.js','// Generated by TW-01 resolver. Do not edit.\nexport default '+json(rows).trim()+';\n');write(download+'dimensions-TW-01.json',json(rows));
write(download+'dimensions-TW-01.csv','family,per_tray_U,total_U,HP,metal_W_mm,metal_D_mm,metal_H_mm,complete_W_mm,complete_D_mm,complete_H_mm,lid_mm,manufacturingApproved\n'+rows.map(r=>[r.id,r.perTrayU,r.totalU,r.hp,...r.metal,...r.complete,r.lidDepth,false].join(',')).join('\n')+'\n');
// Fixed ZIP metadata and sorted input paths. The source bundle mirrors repo paths.
const sourceList=['project/two-way/study-spec.json','engineering/two-way/AGENTS.md'];
function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true}).sort((a,b)=>a.name<b.name?-1:a.name>b.name?1:0)){if(['.venv','__pycache__','evidence','node_modules'].includes(e.name))continue;const p=path.join(dir,e.name);if(e.isDirectory())walk(p);else sourceList.push(path.relative(REPO,p));}}
walk(ROOT);walk(path.join(ROOT,'../f5-reference'));sourceList.push(...Object.keys(D.inputHashes));
for(const file of sourceList)inputs[file]=sha(fs.readFileSync(path.join(REPO,file)));
const zipPath=download+'source-TW-01.zip';fs.mkdirSync(path.dirname(path.join(OUT,zipPath)),{recursive:true});
cp.execFileSync('python3',['-c',`import sys,json,zipfile,pathlib
v=json.load(sys.stdin)
with zipfile.ZipFile(v['out'],'w',compression=zipfile.ZIP_DEFLATED,compresslevel=9) as z:
 for name in sorted(set(v['files'])):
  i=zipfile.ZipInfo(name,(2020,1,1,0,0,0));i.compress_type=zipfile.ZIP_DEFLATED;i.external_attr=0o100644<<16
  z.writestr(i,(pathlib.Path(v['repo'])/name).read_bytes())
`],{input:JSON.stringify({out:path.join(OUT,zipPath),repo:REPO,files:sourceList})});files.push(zipPath);
const manifest={schema:'zudo-case-two-way-artifacts/1',revision:'TW-01',manufacturingApproved:false,sourceCommit:TwoWaySpec.sourceCommit,inputHashes:{...D.inputHashes,...inputs},fidelity:{rail:D.railFidelity,pcb:D.pcbFidelity,hardware:'provisional display envelopes; not manufacturing geometry'},artifacts:files.filter(f=>f.startsWith('public/')).sort().map(f=>{const b=fs.readFileSync(path.join(OUT,f));if(b.length>25*1024*1024)throw Error('Asset exceeds 25 MiB: '+f);return {path:f,sha256:sha(b),bytes:b.length,role:f.endsWith('.glb')?'viewing-mesh':f.endsWith('.html')?'preview':f.endsWith('.zip')?'source':'config-or-data',revision:'TW-01',units:f.endsWith('.glb')?'metres':'mm',upAxis:f.endsWith('.glb')?'Y':'Z',manufacturingApproved:false};})};
write('project/two-way/artifact-manifest.json',json(manifest));write(download+'manifest-TW-01.json',json(manifest));
if(check){const bad=files.filter(f=>!fs.existsSync(path.join(REPO,f))||!fs.readFileSync(path.join(REPO,f)).equals(fs.readFileSync(path.join(OUT,f))));fs.rmSync(OUT,{recursive:true,force:true});if(bad.length)throw Error('Generated drift: '+bad.join(', '));}
console.log(`${check?'Checked':'Generated'} ${files.length} TW-01 artifacts`);

function glb(s){
 const d=M.dimensions(s),g=G.buildGeometry(s,d),chunks=[],views=[],accessors=[],meshes=[],nodes=[];let offset=0;
 function attr(values,type,n){const b=Buffer.alloc(values.length*4);values.forEach((v,i)=>b.writeFloatLE(v,i*4));chunks.push(b);const view=views.push({buffer:0,byteOffset:offset,byteLength:b.length,target:34962})-1;offset+=b.length;const a={bufferView:view,componentType:5126,count:values.length/n,type};if(type==='VEC3'){a.min=Array(n).fill(Infinity);a.max=Array(n).fill(-Infinity);values.forEach((v,i)=>{a.min[i%n]=Math.min(a.min[i%n],v);a.max[i%n]=Math.max(a.max[i%n],v);});}return accessors.push(a)-1;}
 for(const key of ['base','lid','world','ring']){const v=g[key].v;if(!v.length)continue;const ps=[],ns=[],cs=[];for(let i=0;i<v.length;i+=9){let p=v.slice(i,i+3),n=v.slice(i+3,i+6);if(key==='lid'){p=M.lidPoint(p,s,d);n=M.lidNormal(n,s);}ps.push(p[0]/1000,p[2]/1000,-p[1]/1000);ns.push(n[0],n[2],-n[1]);cs.push(...v.slice(i+6,i+9));}const mi=meshes.push({name:key,primitives:[{attributes:{POSITION:attr(ps,'VEC3',3),NORMAL:attr(ns,'VEC3',3),COLOR_0:attr(cs,'VEC3',3)},mode:4}]})-1;nodes.push({name:key,mesh:mi});}
 const body={asset:{version:'2.0',generator:'ZUDO CASE TW-01'},scene:0,scenes:[{nodes:nodes.map((_,i)=>i)}],nodes,meshes,bufferViews:views,accessors,buffers:[{byteLength:offset}],extras:{revision:'TW-01',units:'metres',upAxis:'Y',manufacturingApproved:false,loadRated:false,fidelity:D.pcbFidelity}};
 let j=Buffer.from(JSON.stringify(body));j=Buffer.concat([j,Buffer.alloc((4-j.length%4)%4,32)]);const b=Buffer.concat(chunks),header=Buffer.alloc(20),bh=Buffer.alloc(8);header.writeUInt32LE(0x46546c67);header.writeUInt32LE(2,4);header.writeUInt32LE(28+j.length+b.length,8);header.writeUInt32LE(j.length,12);header.writeUInt32LE(0x4e4f534a,16);bh.writeUInt32LE(b.length);bh.writeUInt32LE(0x004e4942,4);return Buffer.concat([header,j,bh,b]);
}
