"""Offline browser/UI checks, not mechanical approval."""
from pathlib import Path
import json
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]
results=[]
def check(name,ok,detail=None):
 results.append(dict(name=name,passed=bool(ok),detail=detail))
 if not ok:raise AssertionError(name+': '+str(detail))
with sync_playwright() as p:
 browser=p.chromium.launch(executable_path='/usr/bin/chromium',args=['--no-sandbox','--disable-dev-shm-usage'])
 page=browser.new_page(viewport={'width':1500,'height':1060},device_scale_factor=1,accept_downloads=True)
 errors=[];requests=[]
 page.on('pageerror',lambda e:errors.append(str(e)))
 page.on('request',lambda r:requests.append(r.url))
 page.set_content((ROOT/'zudo-case-F5.html').read_text(),wait_until='load')
 page.wait_for_function('window.FoldApp?.ready')
 def settle():page.wait_for_function('!FoldApp.pending');page.wait_for_timeout(55)
 def change(v):page.evaluate('(v)=>FoldApp.setState(v)',v);settle()
 check('offline start with source-frame view',page.evaluate('FoldApp.ready&&FoldApp.state.pose==="frame"&&FoldApp.lastError===null'))
 mode=page.evaluate('FoldApp.viewer.mode')
 for fam in ['compact','performance','twin40']:
  page.locator(f'[data-family="{fam}"]').click();settle()
  for pose in ['frame','closed','joint','play','trunk','packing','parts','hinge']:
   page.locator(f'[data-pose="{pose}"]').click();settle()
   check(f'{fam}/{pose}: control and finite scene',page.evaluate('([f,p])=>FoldApp.state.preset===f&&FoldApp.state.pose===p&&FoldApp.viewer.bounds().max.every(Number.isFinite)&&FoldApp.lastError===null',[fam,pose]))
  if fam=='twin40':check('C selection sets 70 mm lid without altering frame',page.evaluate('FoldApp.state.lidDepth===70&&Math.abs(FoldApp.config().derived.frame.rearReach-61.95092538037109)<1e-6'))
  if fam=='performance':check('B shows two source 3U units and 1 mm gap','Two unchanged 3U' in page.locator('#frameInfo').inner_text())
 page.locator('[data-pose="frame"]').click();settle()
 page.locator('#frameExplode').fill('12');page.locator('#frameExplode').dispatch_event('input');settle()
 check('side-layer explode slider enters frame view',page.evaluate('FoldApp.state.frameExplode===12&&FoldApp.state.pose==="frame"'))
 check('exploded view not presented as packed fit','Exploded inspection' in page.locator('#frameFit').inner_text())
 change({'preset':'twin40','lidDepth':48,'frameExplode':0})
 check('48 mm C lid fails in visible frame status',page.locator('#frameFit').evaluate('e=>e.classList.contains("frame-error")'))
 check('48 mm C lid warns that board is NOT trimmed','NOT trimmed' in page.locator('#checkBanner').inner_text())
 check('48 mm C retains full source board',page.evaluate('Math.abs(FoldApp.config().derived.frame.rearReach-61.95092538037109)<1e-6'))
 change({'lidDepth':70})
 check('70 mm C clears floor nominally',not page.locator('#frameFit').evaluate('e=>e.classList.contains("frame-error")'))
 page.locator('#reset').click();settle()
 page.locator('#profile').select_option('elbow');settle()
 check('low profile controls retain intended 58 mm study',page.evaluate('FoldApp.state.gap===58&&FoldApp.config().derived.free===8'))
 page.locator('#straps').uncheck();settle()
 check('straps removed exposes retention limitation','does NOT prevent separation' in page.locator('#checkBanner').inner_text())
 page.locator('#straps').check();settle()
 page.locator('#collar').select_option('hinged');settle()
 check('optional hinges still do not connect loaded trays',page.evaluate('FoldApp.config().derived.hingeCount===2&&!FoldApp.config().derived.caseToCaseHinge'))
 page.locator('#reset').click();settle()
 change({'pose':'joint','jointLift':18})
 check('joint explosion warning retained','not tensioned' in page.locator('#checkBanner').inner_text())
 change({'pose':'closed','gap':48,'jointLift':0})
 check('impossible front gap warns','overlap' in page.locator('#checkBanner').inner_text())
 change({'gap':72,'trunkW':300,'trunkD':250,'trunkH':200})
 check('too-small trunk warning retained','too small' in page.locator('#checkBanner').inner_text())
 page.locator('#reset').click();settle()
 for k in ['highlight','patch','cutaway','envelopes','structure']:
  old=page.locator('#'+k).is_checked();page.locator('#'+k).set_checked(not old);settle()
  check(k+' toggle',page.evaluate('(k)=>FoldApp.state[k]===document.getElementById(k).checked',k))
  page.locator('#'+k).set_checked(old);settle()
 for v in ['top','side','back','iso']:
  page.locator(f'[data-view="{v}"]').click();settle()
  check('camera '+v,page.evaluate('(v)=>FoldApp.state.view===v',v))
 page.locator('#viewer').focus();old=page.evaluate('FoldApp.viewer.camera.azimuth');page.keyboard.press('ArrowLeft')
 check('keyboard orbit changes azimuth',old!=page.evaluate('FoldApp.viewer.camera.azimuth'))
 page.locator('#full').click();page.wait_for_timeout(80)
 check('full-size viewer expands',page.locator('#stage').evaluate('e=>e.classList.contains("expanded")'))
 page.keyboard.press('Escape');page.wait_for_timeout(80)
 check('Escape closes full-size viewer',not page.locator('#stage').evaluate('e=>e.classList.contains("expanded")'))
 with page.expect_download() as item:page.locator('#saveConfig').click()
 saved=ROOT/'tests/roundtrip-F5.json';item.value.save_as(saved);data=json.loads(saved.read_text())
 check('setup schema and source provenance exported',data['schema']=='zudo-case-study/5' and data['derived']['frame']['sourceCommit'].startswith('6a13d80'))
 check('setup records PCB preview fidelity','approximated' in data['derived']['frame']['pcbGeometry'])
 change({'gap':85});page.locator('#fileInput').set_input_files(saved);settle()
 check('saved setup restores gap',page.evaluate('FoldApp.state.gap')==data['state']['gap'])
 bad=ROOT/'tests/invalid-setup.json';bad.write_text(json.dumps({'schema':'zudo-case-study/4','state':{'gap':72}}))
 page.locator('#fileInput').set_input_files(bad);settle()
 check('old setup rejected without reinterpreting old frame assumptions','not loaded' in page.locator('#toast').inner_text())
 with page.expect_download() as item:page.locator('#png').click()
 item.value.save_as(ROOT/'tests/export-test-F5.png')
 check('PNG export',(ROOT/'tests/export-test-F5.png').stat().st_size>10000)
 page.locator('#reset').click();settle()
 page.wait_for_timeout(5200)  # Let download/import toasts clear before evidence captures.
 page.screenshot(path=str(ROOT/'previews/workbench-desktop.png'))
 for width in [320,390,768,1200,1600]:
  page.set_viewport_size({'width':width,'height':900});page.wait_for_timeout(120)
  extra=page.evaluate('document.documentElement.scrollWidth-innerWidth')
  check(f'no page overflow at {width}px',extra<=1,extra)
  check(f'canvas visible at {width}px',page.locator('#viewer').bounding_box()['width']>200)
  if width==390:page.screenshot(path=str(ROOT/'previews/workbench-mobile.png'))
 check('source-fidelity explanation is visible in document','rounded hole/slot contours are display approximations' in page.locator('.scope').inner_text())
 check('no JavaScript errors',not errors,errors)
 check('no network needed',not [u for u in requests if u.startswith(('http:','https:'))],requests)
 browser.close()
(ROOT/'tests/browser-results.json').write_text(json.dumps({'revision':'F5','renderer':mode,'checks':len(results),'passed':all(r['passed'] for r in results),'results':results},indent=2)+'\n')
print(len(results),'checks passed; renderer:',mode)
