/* Source-fidelity, mounting-datum, nominal envelope and regression tests.
 * These are not physical fit, strength or manufacturing approval tests.
 */
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
require('../source/frame-data.js');require('../source/frame.js');require('../source/model.js');require('../source/renderer.js');require('../source/geometry.js');
const M=FoldModel,G=FoldGeometry,F=FoldFrame,R=FoldRenderer,D=ZudoFrameData;
const near=(a,b,e=1e-7)=>assert.ok(Math.abs(a-b)<=e,`${a} != ${b}`);
function make(id='performance',profile='straight',collar='loose'){
 const p=M.presets[id],pr=M.profiles[profile];return {...M.defaults,preset:id,pose:'closed',baseDepth:p.baseDepth,lidDepth:p.lidDepth,profile,collar,...Object.fromEntries(['gap','plugBase','plugLid','bend','knobBase','knobLid','elbow'].map(k=>[k,pr[k]]))};
}
function bounds(m,xf=p=>p){const lo=[Infinity,Infinity,Infinity],hi=[-Infinity,-Infinity,-Infinity];for(let i=0;i<m.v.length;i+=9){const p=xf(m.v.slice(i,i+3));for(let j=0;j<3;j++){lo[j]=Math.min(lo[j],p[j]);hi[j]=Math.max(hi[j],p[j]);}}return{min:lo,max:hi};}
const SHAS={'40':'178fd2e720d83b92f2430603e5592c5854ca2087','60':'0233c8735a777e0081f2a9e347ed887668588208'};
for(const hp of ['40','60']){
 test(`${hp}HP original JSON matches pinned Git blob`,()=>{const b=fs.readFileSync(path.join(__dirname,`../reference/zudo-case/rail${hp}_mesh.json`));assert.equal(crypto.createHash('sha1').update(Buffer.concat([Buffer.from(`blob ${b.length}\0`),b])).digest('hex'),SHAS[hp]);});
 test(`${hp}HP baked geometry retains all original vertices and indices`,()=>{const r=JSON.parse(fs.readFileSync(path.join(__dirname,`../reference/zudo-case/rail${hp}_mesh.json`),'utf8'));assert.deepEqual(D.rails[hp].positions,r.positions);assert.deepEqual(D.rails[hp].indices,r.indices);assert.equal(D.rails[hp].triangleCount,592);});
}
test('source commit is pinned in data and frame parts',()=>{assert.equal(D.commit,'6a13d80d816b0247ab9eee761c29c1fb786b76cc');const s=make();F.parts(s,M.dimensions(s)).filter(p=>p.type==='solid').forEach(p=>assert.equal(p.sourceCommit,D.commit));});
test('3U and 7U fixer exteriors remain source-size, not rectangular placeholders',()=>{near(Math.max(...D.panels.fixer3u.outer.map(p=>p[0])),134.53186);near(Math.max(...D.panels.fixer3u.outer.map(p=>p[1])),29.990042);near(Math.max(...D.panels.fixer7u.outer.map(p=>p[0])),314.754456);near(Math.max(...D.panels.fixer7u.outer.map(p=>p[1])),60.015381);assert.ok(D.panels.fixer7u.outer.some(p=>p[0]===0&&p[1]===29.990042));assert.ok(D.panels.fixer7u.outer.some(p=>p[1]===59.980083));});
test('PCB fidelity is explicitly separate from source rail fidelity',()=>{assert.equal(D.panels.fixer3u.cutoutFidelity,'bounds-based visual curve approximation');assert.equal(D.panels.fixer7u.cutoutCount,24);assert.equal(D.panels.padder3u.cutoutFidelity,'source polygon vertices');assert.equal(D.panels.padder1u.cutoutCount,3);});
test('all four PCB parts are separate 1.6 mm layers with through holes',()=>{for(const p of Object.values(D.panels)){near(p.thickness,1.6);near(F.bounds(p.positions).size[0],1.6);assert.ok(p.cutoutCount>0);assert.equal(p.manufacturingApproved,false);}});
test('7U uses two 3U padders plus an unchanged 1U padder per side',()=>{assert.deepEqual(D.units['7u'].padders,[{kind:'padder3u',u:0,v:0},{kind:'padder3u',u:134.53186,v:0},{kind:'padder1u',u:269.039027,v:-.025081}]);});
test('source padder-hole offsets were not recentered',()=>{const p=D.panels.padder3u.cutouts[0];near((Math.min(...p.map(x=>x[0]))+Math.max(...p.map(x=>x[0])))/2,6.153823);near(D.units['3u'].rails[0][0],5.997998);});
for(const id of Object.keys(M.presets)){
 const expected={compact:[2,2,2,4],performance:[4,4,4,8],twin40:[6,2,6,10]}[id];
 test(`${id}: actual per-tray rail / fixer / padder / spacer counts`,()=>{const d=M.dimensions(make(id)),p=F.parts(make(id),d);['rail','fixer','padder','spacer'].forEach((role,i)=>assert.equal(p.filter(x=>x.role===role).length,expected[i]));});
 test(`${id}: all original rails receive proper rigid rotations only`,()=>{const s=make(id),d=M.dimensions(s);for(const p of F.parts(s,d).filter(p=>p.role==='rail')){const a=p.matrix,r=[[a[0],a[1],a[2]],[a[4],a[5],a[6]],[a[8],a[9],a[10]]];for(const v of r)near(Math.hypot(...v),1);near(r[0][0]*(r[1][1]*r[2][2]-r[1][2]*r[2][1])-r[0][1]*(r[1][0]*r[2][2]-r[1][2]*r[2][0])+r[0][2]*(r[1][0]*r[2][1]-r[1][1]*r[2][0]),1);near(p.bounds.size[0],d.rail);assert.deepEqual(p.indices,D.rails[String(d.hp)].indices);near(p.bounds.max[2],-2,3e-6);}});
 test(`${id}: 8 mm side space, 1 mm washer and 1.4 mm heads retained`,()=>{const s=make(id),d=M.dimensions(s),p=F.parts(s,d);near((d.W-2*d.t-d.frame.width)/2,8);p.filter(p=>p.role==='spacer').forEach(p=>near(p.x1-p.x0,8));p.filter(p=>p.role==='washer').forEach(p=>near(p.x1-p.x0,1));p.filter(p=>['head','railEnd'].includes(p.role)).forEach(p=>near(p.x1-p.x0,1.4));});
 test(`${id}: source board reach drives the lid fit calculation`,()=>{const s=make(id),d=M.dimensions(s),p=F.parts(s,d).filter(p=>['fixer','padder'].includes(p.role));near(-Math.min(...p.map(p=>p.bounds.min[2])),d.frame.rearReach);near(d.frameRearClearLid,s.lidDepth-d.t-d.frame.rearReach);assert.ok(d.frameRearClearLid>6);});
 test(`${id}: real mounting datums pass through the original fixer slot envelopes`,()=>{for(const inst of M.dimensions(make(id)).frame.units){const u=D.units[inst.kind],holes=D.panels[u.fixer].cutouts;for(const [x,y] of u.mounts)assert.ok(holes.some(h=>x>=Math.min(...h.map(p=>p[0]))&&x<=Math.max(...h.map(p=>p[0]))&&y>=Math.min(...h.map(p=>p[1]))&&y<=Math.max(...h.map(p=>p[1]))));}});
 test(`${id}: dummy screw rows use the original mounting-rail axis datums`,()=>{const s=make(id),d=M.dimensions(s),mods=M.modules(s,d,0).modules;for(const q of mods)assert.ok(d.frame.rows.some(r=>r.screwY.every((x,i)=>Math.abs(x-q.screwY[i])<1e-8)));});
 test(`${id}: separated view preserves each layer thickness and rail mesh`,()=>{const s={...make(id),pose:'frame'},d=M.dimensions(s),a=F.parts(s,d,0),b=F.parts(s,d,12);for(const p of a.filter(p=>p.type==='solid')){const q=b.find(q=>q.id===p.id);p.bounds.size.forEach((v,i)=>near(v,q.bounds.size[i]));if(p.role==='rail')assert.deepEqual(p.positions,q.positions);}});
}
test('B needs no invented 6U PCB: two original 3U assemblies remain 1 mm apart',()=>{const s=make(),d=M.dimensions(s);near(d.D,290);near(d.frame.depth,270.06372);assert.equal(d.frame.units.length,2);d.frame.units.forEach(u=>assert.equal(u.kind,'3u'));near(d.frame.units[1].offset-d.frame.units[0].offset-D.units['3u'].length,1);});
test('C legacy 48 mm lid fails without trimming the 7U PCB',()=>{const s={...make('twin40'),lidDepth:48},d=M.dimensions(s);near(d.frameRearClearLid,-15.45092538037109);const p=F.parts(s,d).filter(p=>p.role==='fixer');p.forEach(p=>near(p.bounds.size[2],60.015381));});
test('C default 70 mm lid leaves the full frame intact',()=>{const s=make('twin40'),d=M.dimensions(s);near(s.lidDepth,70);near(d.frameRearClearLid,6.549074619628911);near(d.closedH,241.5);});
for(const id of Object.keys(M.presets))for(const pro of ['straight','elbow'])for(const collar of ['loose','hinged']){
 test(`${id}/${pro}/${collar}: closed meshes fit declared guarded envelope`,()=>{const s=make(id,pro,collar),d=M.dimensions(s),g=G.buildGeometry(s,d);for(const k of ['base','lid','world','ring']){const b=bounds(g[k],k==='lid'?p=>M.lidPoint(p,s,d):p=>p);if(!g[k].v.length)continue;assert.ok(b.min[0]>=-d.closedW/2-1e-6&&b.max[0]<=d.closedW/2+1e-6,k+' W');assert.ok(b.min[1]>=-d.closedD/2-1e-6&&b.max[1]<=d.closedD/2+1e-6,k+' D');assert.ok(b.min[2]>=d.coreFloor-1e-6&&b.max[2]<=d.coreFloor+d.closedH+1e-6,k+' H');}});
 test(`${id}/${pro}/${collar}: eight views create finite triangle meshes`,()=>{for(const pose of ['frame','closed','play','joint','trunk','packing','parts','hinge']){const s={...make(id,pro,collar),pose},g=G.buildGeometry(s,M.dimensions(s));assert.ok(Object.values(g).some(m=>m.v.length));for(const m of Object.values(g)){assert.equal(m.v.length%27,0);assert.ok(m.v.every(Number.isFinite));}}});
 test(`${id}/${pro}/${collar}: front gap and independent support unchanged`,()=>{const d=M.dimensions(make(id,pro,collar));near(d.free,8);near(d.collarH,d.G-5);assert.equal(d.caseToCaseHinge,false);assert.equal(d.pocket,0);assert.equal(d.loadRated,false);assert.equal(d.frontGapOccupiedByStorage,false);assert.ok(d.playShellClearance>0);assert.ok(d.playFrontClearance>0);});
}
for(const id of Object.keys(M.presets))for(const metal of [1.5,2,2.5])for(const ply of [6,8,10])test(`${id}/${metal}/${ply}: stand pack and locators clear the source-frame bounds`,()=>{const s={...make(id),thickness:metal,ply},d=M.dimensions(s),m=new R.Mesh();G.packedStand(m,s,d);const b=bounds(m);assert.ok(b.min[0]>=-d.W/2&&b.max[0]<=d.W/2);assert.ok(b.min[1]>=-d.D/2&&b.max[1]<=d.D/2);assert.ok(b.min[2]>=0&&b.max[2]<=d.standSleeve);assert.ok(d.frameSideClearance>=1.4-1e-7);assert.ok(d.frameEndClearance>1.4);});
for(const overlap of [4,6,10])for(const fit of [.25,.6,1.2])test(`new seat ${overlap}/${fit}: source-frame-aware return and locating shoe`,()=>{const s={...make(),overlap,seatClearance:fit},d=M.dimensions(s),m=G.closureSection(s,d,100),b=bounds(m);near(d.innerLip,d.seatInner+fit+s.thickness);near(d.frameSideClearance,(d.W-d.frame.width)/2-d.innerLip);near(b.min[1],-d.collarOuter);near(b.max[1],d.innerLip);near(b.min[2],d.rim+d.gasket-overlap);near(b.max[2],d.G-d.rim-d.gasket+overlap);assert.ok(d.frameSideClearance>0);});
for(const id of Object.keys(M.presets))test(`${id}: trunk budget includes guarded fasteners and separate stand sleeve`,()=>{const s=make(id),d=M.dimensions(s);near(d.closedW,d.W+16);near(d.trunkRequired[0],d.closedW+2*s.foam);near(d.trunkRequired[1],d.closedD+2*s.foam);near(d.trunkRequired[2],d.closedH+2*s.foam+13+2*s.ply+4);});
test('default B dimensions and reduced locator intrusion',()=>{const d=M.dimensions(make());[346.4,312,208].forEach((v,i)=>near(v,[d.closedW,d.closedD,d.closedH][i]));[386.4,352,281].forEach((v,i)=>near(v,d.trunkRequired[i]));near(d.frameSideClearance,2.4);near(d.seatWidth,3.5);near(d.usableLid,34.5);});
test('small trunk and impossible patch gap produce negative margins',()=>{const d=M.dimensions({...make(),gap:48,trunkW:300,trunkD:250,trunkH:200});assert.equal(d.trunkFits,false);near(d.free,-16);near(d.frame.width,311.4);});
test('source rails do not mutate when other thickness, depth or pose inputs change',()=>{const before=JSON.stringify(D.rails);for(const pose of ['frame','closed','play'])G.buildGeometry({...make(),pose,thickness:2.5},M.dimensions({...make(),pose,thickness:2.5}));assert.equal(JSON.stringify(D.rails),before);});
test('known purchased hinge dimensions are retained independently of frame update',()=>{const s=make(),d=M.dimensions(s),b=bounds(G.hinge(s,d,180));near(b.max[0]-b.min[0],76);near(b.max[2]-b.min[2],15);near(d.hingeLeaf,35);assert.equal(d.hingeRatingKnown,false);});
test('opposed closed panels and 45 degree playing pose remain independent placements',()=>{const s=make(),d=M.dimensions(s);near(M.lidPoint([0,0,0],s,d)[2],72);near(M.lidNormal([0,0,1],{...s,pose:'play'})[2],Math.SQRT1_2);assert.equal(d.poseIsKinematic,false);});
test('patch endpoints remain attached; no fixed-length cable claim',()=>{for(const pose of ['closed','play']){const s={...make(),pose},d=M.dimensions(s);for(let i=0;i<2;i++){const a=M.crossAnchors(s,d)[i],p=M.cableRoute(s,d,i);M.plugExit(a.base,s,0).forEach((v,k)=>near(v,p[0][k]));M.lidPoint(M.plugExit(a.lid,s,1),s,d).forEach((v,k)=>near(v,p.at(-1)[k]));}assert.match(M.routeBudget(s,d).scope,/not solved/);}});
test('F5 setup retains provenance and separates layout from approval',()=>{const c=M.config(make());assert.equal(c.schema,'zudo-case-study/5');assert.equal(c.derived.frame.sourceCommit,D.commit);for(const k of ['manufacturingApproved','purchasedHardwareFitVerified','loadRated'])assert.equal(c[k],false);});
test('invalid state rejected without remaking a source frame',()=>{for(const p of [{preset:'custom6u'},{frameExplode:-1},{frameExplode:100},{lidDepth:0},{seatClearance:NaN},{straps:'yes'},{pose:'opening'},{kit:'pedestal'}])assert.throws(()=>M.validate({...make(),...p}));});
