"""Offline engineering preview; every candidate mesh comes from the CAD builder."""
from pathlib import Path
import base64,gzip,json

HTML=r'''<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ZUDO CASE · R9 FITFIX</title><style>
*{box-sizing:border-box}body{margin:0;background:#edf0f2;color:#16232c;font:14px/1.6 system-ui,sans-serif}header{padding:14px 24px;border-bottom:1px solid #ccd5db;background:#fff;display:flex;align-items:center;justify-content:space-between;gap:15px}header h1{font-size:17px;letter-spacing:.05em;margin:0}header p{margin:0;font-size:12px;color:#596b78}.badge{font-size:11px;color:#784918;background:#fff3dc;border:1px solid #e7cd9f;border-radius:5px;padding:4px 9px}main{display:grid;grid-template-columns:minmax(0,1fr) 316px;height:calc(100dvh - 75px)}#view{position:relative;min-height:400px;overflow:hidden}canvas{width:100%;height:100%;display:block;touch-action:none}aside{padding:18px;background:#fff;overflow:auto;border-left:1px solid #cdd6dc}h2{font-size:12px;letter-spacing:.1em;color:#59707f;margin:16px 0 8px}button,select{font:inherit;border:1px solid #bac8d2;background:#fff;color:#1f3442;border-radius:5px;padding:8px 10px;cursor:pointer}button:hover{background:#e6f0f4}button.active{background:#1e526c;color:white;border-color:#1e526c}.buttons{display:flex;flex-wrap:wrap;gap:6px}select{width:100%}label{display:block;margin:10px 0}input[type=range]{width:100%}.note{font-size:12px;color:#5b6c77;border-top:1px solid #dce2e6;padding-top:12px;margin-top:20px}#info{font-family:ui-monospace,monospace;font-size:12px;white-space:pre-line;padding:9px;background:#f2f6f8;border-radius:5px}#selection{position:absolute;left:18px;bottom:20px;max-width:90%;padding:8px 12px;background:#ffffffdd;border-radius:5px;font:12px ui-monospace,monospace}#loading{position:absolute;inset:0;display:grid;place-items:center;background:#eef2f4;z-index:2}#caption{position:absolute;top:14px;left:18px;color:#3b596a;font-size:12px;pointer-events:none}@media(max-width:720px){header{padding:12px}header p{display:none}main{display:block;height:auto}#view{height:57dvh;min-height:330px}aside{border-left:0;border-top:1px solid #cdd6dc;padding:15px}#selection{left:10px;bottom:10px}h2{margin-top:14px}}
</style><header><div><h1>ZUDO CASE / R9 FITFIX</h1><p>7U · 40HP — 実肉厚・下辺断面・着座面の修正版</p></div><a href="r9-order-map.html" style="color:#075f70;font-weight:700;background:#e2f4f1;padding:8px 12px;border-radius:6px">Ordered fit tests / 注文パーツの位置 ↗</a><span class="badge">未承認 / 修正候補</span></header><main><div id="view"><div id="loading">3Dを読み込み中…</div><div id="caption"></div><div id="selection">ドラッグ: 回転 ／ ホイール: 拡大 ／ 右ドラッグ: 移動</div></div><aside>
<h2>表示対象</h2><select id="mode"><option value="case">7U40 ケース全体</option></select><h2>実肉厚</h2><div class="buttons"><button id="t1p2" class="active">1.2mm 基本案</button><button id="t1p0">1.0mm 比較案</button></div><h2>蓋の操作</h2><div class="buttons"><button id="closed" class="active">載せる</button><button id="open">真上へ外す</button><button id="travel">バンド2本</button></div><label>持ち上げ量 <span id="riseLabel">0mm</span><input id="lift" type="range" min="0" max="160" value="0"></label><h2>内部と接合部</h2><label><input id="color" type="checkbox" checked> 部品を色分け</label><label><input id="transparent" type="checkbox"> 外板・天板を透過</label><label><input id="section" type="checkbox"> 中央で断面表示</label><label><input id="hardware" type="checkbox" checked> 既存レール・金具を表示</label><div class="buttons"><button id="fit">全体</button><button id="front">正面</button><button id="bottom">底面</button><button id="shot">画像保存</button></div><h2>基準面と寸法</h2><div id="info"></div><p class="note">上端ガードは金属上端に直接着座。蓋もガード上面に着座。隙間は垂直な接着面にだけ設定し、実肉厚は別に保持しています。<br><br>レール・PCB・金具は保存R6から再構成した公称参照。バンドは模式表示です。物理的な嵌合・接着・強度は未検証。1.0mmでは専用の蓋も連動します。異なる厚さの部品を混用しないでください。</p></aside></main><script>__VENDOR__</script><script>
// Canvas fallback for machines without WebGL. Uses the same generated triangles.
class FitfixCanvasRenderer {
 constructor(T){this.T=T;this.domElement=document.createElement('canvas');this.ctx=this.domElement.getContext('2d');this.dirty=true;this.lastKey='';this.ratio=1;this.background='#eaf0f3';this.software=true;}
 setPixelRatio(r){this.ratio=Math.min(r,1.5);}
 setClearColor(v){this.background='#'+v.toString(16).padStart(6,'0');}
 setSize(w,h){this.w=w;this.h=h;this.domElement.width=Math.round(w*this.ratio);this.domElement.height=Math.round(h*this.ratio);this.domElement.style.width=w+'px';this.domElement.style.height=h+'px';this.dirty=true;}
 render(scene,camera){
 const T=this.T;scene.updateMatrixWorld(true);camera.updateMatrixWorld(true);
 const key=camera.matrixWorld.elements.map(x=>x.toFixed(5)).join(',')+'|'+camera.projectionMatrix.elements.map(x=>x.toFixed(5)).join(',');
 if(!this.dirty&&this.lastKey===key)return;this.lastKey=key;this.dirty=false;
 const ctx=this.ctx,W=this.w,H=this.h;ctx.setTransform(this.ratio,0,0,this.ratio,0,0);ctx.globalAlpha=1;ctx.fillStyle=this.background;ctx.fillRect(0,0,W,H);
 const vp=new T.Matrix4().multiplyMatrices(camera.projectionMatrix,camera.matrixWorldInverse),faces=[];
 scene.traverse(o=>{
  if(!o.isMesh||!o.visible)return;
  const positions=o.geometry.attributes.position.array,idx=o.geometry.index.array,mvp=new T.Matrix4().multiplyMatrices(vp,o.matrixWorld),q=mvp.elements,world=o.matrixWorld.elements,verts=[];
  for(let j=0;j<positions.length;j+=3){let x=positions[j],y=positions[j+1],z=positions[j+2],d=q[3]*x+q[7]*y+q[11]*z+q[15];
   verts.push([(q[0]*x+q[4]*y+q[8]*z+q[12])/d,(q[1]*x+q[5]*y+q[9]*z+q[13])/d,(q[2]*x+q[6]*y+q[10]*z+q[14])/d,world[0]*x+world[4]*y+world[8]*z+world[12],x,y,z]);}
  const c=o.material.color,alpha=o.material.opacity,clip=o.material.clippingPlanes?.length;
  for(let j=0;j<idx.length;j+=3){const a=verts[idx[j]],b=verts[idx[j+1]],c0=verts[idx[j+2]];
   if(a[2]<-1||b[2]<-1||c0[2]<-1||a[2]>1||b[2]>1||c0[2]>1)continue;
   if(clip&&(a[3]+b[3]+c0[3])/3<0)continue;
   const area=(b[0]-a[0])*(c0[1]-a[1])-(b[1]-a[1])*(c0[0]-a[0]);
   if(area<=1e-10&&alpha>=1)continue;
   const ux=b[4]-a[4],uy=b[5]-a[5],uz=b[6]-a[6],vx=c0[4]-a[4],vy=c0[5]-a[5],vz=c0[6]-a[6];
   const nx=uy*vz-uz*vy,ny=uz*vx-ux*vz,nz=ux*vy-uy*vx,norm=Math.hypot(nx,ny,nz)||1,light=.58+.42*Math.abs((.35*nx-.45*ny+.82*nz)/norm);
   const col=`rgb(${Math.round(Math.min(1,c.r*light+.10)*255)},${Math.round(Math.min(1,c.g*light+.10)*255)},${Math.round(Math.min(1,c.b*light+.10)*255)})`;
   faces.push({a,b,c:c0,z:(a[2]+b[2]+c0[2])/3,col,alpha});
  }
 });
 faces.sort((a,b)=>b.z-a.z);
 for(const f of faces){ctx.globalAlpha=f.alpha;ctx.fillStyle=f.col;ctx.beginPath();ctx.moveTo((f.a[0]+1)*W/2,(1-f.a[1])*H/2);ctx.lineTo((f.b[0]+1)*W/2,(1-f.b[1])*H/2);ctx.lineTo((f.c[0]+1)*W/2,(1-f.c[1])*H/2);ctx.closePath();ctx.fill();}
 ctx.globalAlpha=1;ctx.fillStyle='#59707f';ctx.font='11px system-ui';ctx.fillText('簡易Canvas描画（WebGLなし） / 断面は表示用の面選別',14,18);
 }
}

(async()=>{const $=id=>document.getElementById(id);try{
const bytes=Uint8Array.from(atob('__DATA__'),c=>c.charCodeAt(0));const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));const data=JSON.parse(await new Response(stream).text());window.fitfixData=data;const T=window.THREE;const viewport=$('view');const trial=document.createElement('canvas');const gl=trial.getContext('webgl2',{antialias:true,preserveDrawingBuffer:true});const renderer=gl?new T.WebGLRenderer({canvas:trial,context:gl,antialias:true,preserveDrawingBuffer:true}):new FitfixCanvasRenderer(T);window.fitfixRenderer=renderer.software?'canvas-fallback':'webgl';renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0xeaf0f3,1);renderer.localClippingEnabled=true;viewport.appendChild(renderer.domElement);const scene=new T.Scene();scene.add(new T.HemisphereLight(0xffffff,0x758595,2.4));const sun=new T.DirectionalLight(0xffffff,3);sun.position.set(300,-400,650);scene.add(sun);const back=new T.DirectionalLight(0xffffff,1.2);back.position.set(-400,100,300);scene.add(back);const camera=new T.PerspectiveCamera(36,1,.1,6000);camera.up.set(0,0,1);const controls=new window.OrbitControls(camera,renderer.domElement);controls.enableDamping=!renderer.software;const clipPlane=new T.Plane(new T.Vector3(1,0,0),0);let group=new T.Group();scene.add(group);let meshes=[],variant='t1p2',mode='case',bandMode=false;const colors={metal:0x8395a0,guards:0xe1a247,lid:0x309baf,lidMetal:0xb2c1ca,rails:0x687780,pcb:0x263e36,hardware:0x8492a0};
function make(item){const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(item.positions,3));geo.setIndex(item.indices);geo.computeVertexNormals();geo.computeBoundingBox();const material=new T.MeshStandardMaterial({color:colors[item.group]||0x789aab,roughness:.62,metalness:['metal','lidMetal'].includes(item.group)?.25:.05,side:T.DoubleSide});const mesh=new T.Mesh(geo,material);mesh.userData=item;group.add(mesh);meshes.push(mesh)}
function dispose(){for(const m of meshes){m.geometry.dispose();m.material.dispose()}scene.remove(group);group=new T.Group();scene.add(group);meshes=[]}
function bands(){if(mode!=='case'||!bandMode||Number($('lift').value)>0)return;const i=data.variants[variant].interface,w=i.guard_exterior_mm[0],d=i.guard_exterior_mm[1],zt=i.lip_top_z_mm+1,zb=-4.5;for(const y of [-d*.27,d*.27])for(const [sx,sy,sz,x,z] of [[w+3,20,1.2,0,zt],[w+3,20,1.2,0,zb],[1.2,20,zt-zb,-w/2-1.5,(zt+zb)/2],[1.2,20,zt-zb,w/2+1.5,(zt+zb)/2]]){const gg=new T.BoxGeometry(sx,sy,sz);gg.translate(x,y,z);make({id:'band-schematic',group:'band',positions:Array.from(gg.attributes.position.array),indices:Array.from(gg.index.array)});gg.dispose()}}
function fill(){dispose();if(mode==='case'){for(const x of data.reference)make(x);for(const x of data.variants[variant].meshes)make(x);bands()}else for(const x of data.coupons[mode].meshes)make(x);style();fit()}
function style(){renderer.dirty=true;for(const id of ['t1p2','t1p0','lift','open','closed','travel','section'])$(id).disabled=mode!=='case';$('closed').classList.toggle('active',!bandMode&&Number($('lift').value)===0);$('open').classList.toggle('active',Number($('lift').value)>0);$('travel').classList.toggle('active',bandMode);const i=data.variants[variant].interface;for(const m of meshes){const kind=m.userData.group;let color=$('color').checked?(colors[kind]||0x343a41):(['rails','hardware'].includes(kind)?0x8c969e:0x20292f);if(kind==='band')color=0x282b30;m.material.color.setHex(color);const transparent=$('transparent').checked&&['metal','lidMetal'].includes(kind);m.material.transparent=transparent;m.material.opacity=transparent?.22:1;m.material.depthWrite=!transparent;m.material.clippingPlanes=$('section').checked?[clipPlane]:[];m.visible=$('hardware').checked||!['rails','pcb','hardware'].includes(kind);m.position.z=mode==='case'&&['lid','lidMetal'].includes(kind)?Number($('lift').value):0} $('riseLabel').textContent=$('lift').value+'mm';$('caption').style.top=renderer.software?'31px':'14px';$('caption').textContent=mode==='case'?'候補部品は今回生成したCADから描画':mode+' — '+data.coupons[mode].description;$('info').textContent=`金属本体: 229.4 × 334 × 91\nガード外形: ${i.guard_exterior_mm.map(x=>x.toFixed(1)).join(' × ')}\n実肉厚: ${i.flat_wall_mm.toFixed(1)} mm\n金属上端: Z 91.0\nガード上面: Z ${i.guard_top_z_mm.toFixed(1)}\n蓋の座面: Z ${i.lid_seat_z_mm.toFixed(1)}\n天板下面: Z ${i.plate_bottom_z_mm.toFixed(1)}\n差し込み: ${i.lid_engagement_mm} mm\n全高とZ座標は別管理`;if(mode!=='case')$('info').textContent=`試験片 ${mode}\n部品をクリックして外形を確認。\nC1-05は1.0mm、その他は基本案。\n金属とPA12を別発注。\n必要数量・材質・比較条件は\nBOMと各manifestを参照。\n現物結果は未記入。`}
function fit(){const bb=new T.Box3().setFromObject(group),center=bb.getCenter(new T.Vector3()),size=bb.getSize(new T.Vector3());const radius=size.length()/2;const half=Math.min(camera.fov*Math.PI/360,Math.atan(Math.tan(camera.fov*Math.PI/360)*camera.aspect));const r=radius/Math.sin(half)*1.12;controls.target.copy(center);camera.position.copy(center).add(new T.Vector3(.8,-1.1,.85).normalize().multiplyScalar(r));camera.near=.05;camera.far=10000;camera.updateProjectionMatrix();controls.update()}
function rebuildKeepView(){const pos=camera.position.clone(),target=controls.target.clone();fill();camera.position.copy(pos);controls.target.copy(target);controls.update()}
for(const id of Object.keys(data.coupons))$('mode').add(new Option(id+' · '+({'C1':'上端','C2':'蓋の着座','C4':'下辺 / 底＋壁','C5':'上端 / 2立板'}[id.slice(0,2)]||'試験片'),id));$('mode').onchange=()=>{mode=$('mode').value;if(mode!=='case'){$('section').checked=false;$('lift').value=0;}fill()};for(const v of ['t1p2','t1p0'])$(v).onclick=()=>{variant=v;for(const a of ['t1p2','t1p0'])$(a).classList.toggle('active',a===v);fill()};for(const id of ['color','transparent','section','hardware'])$(id).onchange=style;$('lift').oninput=()=>{if(bandMode){bandMode=false;rebuildKeepView()}style()};$('closed').onclick=()=>{bandMode=false;$('lift').value=0;rebuildKeepView()};$('open').onclick=()=>{bandMode=false;$('lift').value=130;fill()};$('travel').onclick=()=>{bandMode=true;$('lift').value=0;fill()};$('fit').onclick=fit;$('front').onclick=()=>{const c=controls.target.clone(),r=camera.position.distanceTo(c);camera.position.set(c.x,c.y-r,c.z);controls.update()};$('bottom').onclick=()=>{const c=controls.target.clone(),r=camera.position.distanceTo(c);camera.position.set(c.x+.01,c.y-.01,c.z-r);controls.update()};$('shot').onclick=()=>{renderer.render(scene,camera);const a=document.createElement('a');a.href=renderer.domElement.toDataURL('image/png');a.download='zudo-r9-fitfix-'+mode+'.png';a.click()};const raycaster=new T.Raycaster(),mouse=new T.Vector2();let down;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>4)return;const r=renderer.domElement.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(mouse,camera);const hit=raycaster.intersectObjects(meshes.filter(x=>x.visible))[0];if(hit){const b=hit.object.geometry.boundingBox.getSize(new T.Vector3());$('selection').textContent=hit.object.userData.id+' — '+[b.x,b.y,b.z].map(x=>x.toFixed(2)).join(' × ')+' mm'}});function resize(){renderer.setSize(viewport.clientWidth,viewport.clientHeight);camera.aspect=viewport.clientWidth/viewport.clientHeight;camera.updateProjectionMatrix();fit()}new ResizeObserver(resize).observe(viewport);fill();resize();$('loading').style.display='none';window.fitfixReady=true;function draw(){requestAnimationFrame(draw);controls.update();renderer.render(scene,camera)}draw();}catch(e){$('loading').textContent='表示できません: '+e.message;console.error(e)}})();</script></html>'''

def make_preview(data,vendor,path):
    payload=base64.b64encode(gzip.compress(json.dumps(data,separators=(',',':')).encode(),mtime=0)).decode()
    html=HTML.replace('__VENDOR__',Path(vendor).read_text().replace('</script','<\\/script')).replace('__DATA__',payload)
    Path(path).write_text(html,encoding='utf-8')
